### ISSUE TITLE
BasketSlice Feature Issue

### ISSUE THREAD

**Issue by vladyslav-chornohuz** [JM-629/Food-Delivery-Mobile-App#3]
Although createSlice with Redux Toolkit handles immutability internally using Immer, directly modifying state properties like state.items.push(action.payload) may seem to violate immutability rules in a typical Redux setup. 

This could confuse developers who are not familiar with how Redux Toolkit manages immutability.

If you prefer being explicit or ensuring clarity for developers who might not be familiar with Immer, you could use the spread operator to update state immutably. 

However, since createSlice is designed to handle immutability, the current approach is valid.

**Comment by JM-629** [comment]
Yes. You are right. Let me fix them.
